import type { NextPage } from "next";
import Head from "next/head";
import Adress from "../components/adress";
import HeadingText from "../components/hedingText";
import NavigationBar from "../components/navigationBar";
import OrdersList from "../components/orders";
import SearchBar from "../components/searchBar";
import SinIn from "../components/sinIn";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row gap-2 justify-around">
        <HeadingText text="Babaju.com" />
        <Adress City="Asansol" pin="715556" full="Ruse Aprtmanet" />
        <SearchBar />
        <SinIn />
        <OrdersList />
      </div>
      <NavigationBar />
    </>
  );
};

export default Home;
