import type { NextPage } from "next";
import Head from "next/head";
import NavigationBar from "../components/navigationBar";

const Home: NextPage = () => {
  return (
    <div className="m-1">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar title={"BOBONG.com"} />
      <main>
        <div className=" origin-center -z-50 absolute top-1/3 left-1/3 blur-xl">
          <div className="animate-blob absolute top-1 w-72 h-72 bg-[#a0fefb] rounded-full mix-blend-multiply"></div>
          <div className="animate-blob absolute top-16 left-16 w-72 h-72 bg-rose-400 rounded-full mix-blend-multiply"></div>
          <div className="animate-blob absolute top-1 left-24 w-72 h-72 bg-pink-400 rounded-full mix-blend-multiply"></div>
        </div>
      </main>
    </div>
  );
};

export default Home;
